import java.text.DecimalFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.io.File;         // Import the File class
import java.io.FileNotFoundException;  // Import this class to handle errors
import java.io.IOException;
import java.util.ArrayList;
import java.util.Formatter;
import java.util.Scanner; // Import the Scanner class to read text files


/**
 *
 * @author Ibango
 */
public class VendingMachine extends javax.swing.JFrame {
    
    //saveStock saves changes to stocks to a file
    public void saveStock(String updStock){
        try {
            Formatter oFile = new Formatter("stock.txt");
            oFile.format("%s",updStock); // write information about the project to file
            oFile.close(); // close file after finish writing   
	} catch (IOException e) {
            System.out.println("**An error occurred writing to stock.txt file**");
            e.printStackTrace();
	}	
    }  
    
    // read stock from txt file to a textArea on form
    public void readStock(){
        String data = "";
        try {
            File myObj = new File("stock.txt");
            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                data += myReader.nextLine() +"\n";
                
            }
            
            // save stock name and quantity in an array(stockList)
            String tmpData = data;
            tmpData = tmpData.replace("\n", ", ");
            String[] tokens = tmpData.split(", ");
            
            stockList = new ArrayList<>();
            for(int i = 0; i< tokens.length; i++){
                    stockList.add(tokens[i]);  
            }
            
            jTextArea1.setText(data);
            myReader.close();
            
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }
    
    /**
     * Creates new form myForm1
     */
    public VendingMachine() {
        
        initComponents();
        readStock(); // call readStock method
      
        prices = new HashMap<>();
        // align price with the product in a hashmap
        prices.put(cokeCbox, 12.0);
        prices.put(breadCbox, 12.0);
        prices.put(chocolateBarCbox, 30.0);
        prices.put(granolaBarsCbox, 63.95);
        prices.put(lollipopCbox, 10.90 );
        prices.put(riceCrispyCbox,64.0);
        prices.put(juiceCbox, 15.0);
        prices.put(waterCbox, 13.0);
        prices.put(spriteCbox, 12.50);
        prices.put(biscuitCbox, 55.0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        changeTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        chocolateBarCbox = new javax.swing.JCheckBox();
        riceCrispyCbox = new javax.swing.JCheckBox();
        lollipopCbox = new javax.swing.JCheckBox();
        breadCbox = new javax.swing.JCheckBox();
        granolaBarsCbox = new javax.swing.JCheckBox();
        juiceCbox = new javax.swing.JCheckBox();
        spriteCbox = new javax.swing.JCheckBox();
        waterCbox = new javax.swing.JCheckBox();
        cokeCbox = new javax.swing.JCheckBox();
        biscuitCbox = new javax.swing.JCheckBox();
        clearBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        moneyTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        stockMsg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("vendind machine");
        setResizable(false);

        buyBtn.setText("buy");
        buyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vending Machine");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("Welcome !");

        changeTxtField.setEditable(false);
        changeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Insert money(Rands):");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0)));

        chocolateBarCbox.setText("Chocolate bar R30");

        riceCrispyCbox.setText("Rice Crispy R64");

        lollipopCbox.setText("Lollipop R10.90");
        lollipopCbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lollipopCboxActionPerformed(evt);
            }
        });

        breadCbox.setText("Bread R12 ");

        granolaBarsCbox.setText("Granola Bars  R63.95");
        granolaBarsCbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                granolaBarsCboxActionPerformed(evt);
            }
        });

        juiceCbox.setText("Juice R15 ");

        spriteCbox.setText("Sprite R12.50 ");

        waterCbox.setText("Water R13");

        cokeCbox.setText("Coke 12R");

        biscuitCbox.setText("Biscuit R55");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(riceCrispyCbox)
                    .addComponent(chocolateBarCbox)
                    .addComponent(lollipopCbox)
                    .addComponent(granolaBarsCbox)
                    .addComponent(breadCbox))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(biscuitCbox)
                    .addComponent(spriteCbox)
                    .addComponent(juiceCbox)
                    .addComponent(waterCbox)
                    .addComponent(cokeCbox))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chocolateBarCbox)
                    .addComponent(spriteCbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(riceCrispyCbox)
                    .addComponent(juiceCbox))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(granolaBarsCbox)
                    .addComponent(cokeCbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lollipopCbox)
                    .addComponent(waterCbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(breadCbox)
                    .addComponent(biscuitCbox))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Change:");

        moneyTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Select items you want");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        stockMsg1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        stockMsg1.setText("Stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moneyTxtField)
                            .addComponent(changeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buyBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))))
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockMsg1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 106, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(stockMsg1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(moneyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(changeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buyBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBtn))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBtnActionPerformed
        // purchase items selected if there is enough money
   
        Double money = 0.0;
        DecimalFormat numberFormat = new DecimalFormat("#.00"); // two decial place format
        //String strMoney = moneyTxtField.getText();
        if(moneyTxtField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "There\'s no money");
            return;
        }
        
        try{
            money = Double.parseDouble(moneyTxtField.getText());
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, " wrong money");
            return;
        }
        
        Integer stockInt = 0;
        boolean anyIsSelected = false; // check if any item is selected 
        // deduce from money inserted according to selected items
        for(javax.swing.JCheckBox item: prices.keySet()){
            if(item.isSelected()){
                // code bellow deducts from stock before buying 
               for(int i = 0; i < stockList.size(); i+=2)
                   if(item.getText().contains(stockList.get(i))){
                       stockInt = Integer.parseInt(stockList.get(i+1));
                       if(stockInt == 0){
                           JOptionPane.showMessageDialog(this, " Out of stock for " + item.getText());
                           item.setSelected(false);
                          return;
                         }
                       stockInt--; // decrease stock of item
                       stockList.set(i+1, stockInt.toString());
                   }
               
               
                money -= prices.get(item);
                
                anyIsSelected = true;
            }
        }
        
        // first check that user has selected any item or not
        if(!anyIsSelected){
            JOptionPane.showMessageDialog(this, "No item is selected");
            return;
        }
        // check to see if user's money is enough or not
        if(money < 0){ // money is not enough
            Double owed = Math.abs(money);
             JOptionPane.showMessageDialog(this, "Sorry! your money is not enough ! short of: " + numberFormat.format(owed));
        } else{ // purchase is complete
               
              // update stock available
            String updStock ="";
            for(int i = 0; i <stockList.size();i+=2) {
                updStock += stockList.get(i) +", "+ stockList.get(i+1) +"\n";
            }
            // Save stock list to file
            saveStock(updStock);
            jTextArea1.setText(updStock);
             // Output change
            //Double.toString(money)
            changeTxtField.setText(numberFormat.format(money));
            String message = "========ITEMS BOUGHT============= \n";
            
            for(javax.swing.JCheckBox item: prices.keySet()){
                if(item.isSelected()){
                    message += item.getText()+"\n";
            }
        }
            JOptionPane.showMessageDialog(this, "Your Purchase has been completed\n" + message);
        }
        
        
    }//GEN-LAST:event_buyBtnActionPerformed

    private void changeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeTxtFieldActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        ///Clear everything user has selected
        breadCbox.setSelected(false);
        chocolateBarCbox.setSelected(false);
        granolaBarsCbox.setSelected(false);
        lollipopCbox.setSelected(false);
        riceCrispyCbox.setSelected(false);
        juiceCbox.setSelected(false);
        waterCbox.setSelected(false);
        spriteCbox.setSelected(false);
        cokeCbox.setSelected(false);
     
        moneyTxtField.setText(null);
        changeTxtField.setText(null);
        JOptionPane.showMessageDialog(this, "Order has been cleared!");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // ask user if he wnats to cancell/ exit the order
         int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to cancel the order?", "Cancel order message",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
          dispose();
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void moneyTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyTxtFieldActionPerformed

    private void granolaBarsCboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_granolaBarsCboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_granolaBarsCboxActionPerformed

    private void lollipopCboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lollipopCboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lollipopCboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendingMachine().setVisible(true);
            }
        });
    }
    
    
    private ArrayList<String> stockList;
    private HashMap<javax.swing.JCheckBox, Double> prices; // will store price of items
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox biscuitCbox;
    private javax.swing.JCheckBox breadCbox;
    private javax.swing.JButton buyBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField changeTxtField;
    private javax.swing.JCheckBox chocolateBarCbox;
    private javax.swing.JButton clearBtn;
    private javax.swing.JCheckBox cokeCbox;
    private javax.swing.JCheckBox granolaBarsCbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox juiceCbox;
    private javax.swing.JCheckBox lollipopCbox;
    private javax.swing.JTextField moneyTxtField;
    private javax.swing.JCheckBox riceCrispyCbox;
    private javax.swing.JCheckBox spriteCbox;
    private javax.swing.JLabel stockMsg1;
    private javax.swing.JCheckBox waterCbox;
    // End of variables declaration//GEN-END:variables
}
